services:
  web:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules   # keep node_modules in container only
      - /app/package-lock.json   # override to container-only
    ports:
      - "3000:3000"
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
