version: "3.8"
services:
  amazonclone:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    
